# 文件读写

写入测试文件：

In [1]:
%%file test.txt
this is a test file.
hello world!
python is good!
today is a good day.

Writing test.txt


## 读文件

使用 `open` 函数来读文件，使用文件名的字符串作为输入参数：

In [2]:
f = open('test.txt')

默认以读的方式打开文件，如果文件不存在会报错。

可以使用 `read` 方法来读入文件中的所有内容：

In [3]:
text = f.read()
print(text)

this is a test file.
hello world!
python is good!
today is a good day.


也可以按照行读入内容，`readlines` 方法返回一个列表，每个元素代表文件中每一行的内容：

In [4]:
f = open('test.txt')
lines = f.readlines()
print(lines)

['this is a test file.\n', 'hello world!\n', 'python is good!\n', 'today is a good day.']


使用完文件之后，需要将文件关闭。

In [5]:
f.close()

事实上，我们可以将 `f` 放在一个循环中，得到它每一行的内容：

In [6]:
f = open('test.txt')
for line in f:
    print(line)
f.close()

this is a test file.

hello world!

python is good!

today is a good day.


删除刚才创建的文件：

In [7]:
import os
os.remove('test.txt')

## 写文件

我们使用 `open` 函数的写入模式来写文件：

In [8]:
f = open('myfile.txt', 'w')
f.write('hello world!')
f.close()

使用 `w` 模式时，如果文件不存在会被创建，我们可以查看是否真的写入成功：

In [9]:
print(open('myfile.txt').read())

hello world!


如果文件已经存在， `w` 模式会覆盖之前写的所有内容：

In [10]:
f = open('myfile.txt', 'w')
f.write('another hello world!')
f.close()
print(open('myfile.txt').read())

another hello world!


除了写入模式，还有追加模式 `a` ，追加模式不会覆盖之前已经写入的内容，而是在之后继续写入：

In [11]:
f = open('myfile.txt', 'a')
f.write('... and more')
f.close()
print(open('myfile.txt').read())

another hello world!... and more


写入结束之后一定要将文件关闭，否则可能出现内容没有完全写入文件中的情况。

还可以使用读写模式 `w+`：

In [12]:
f = open('myfile.txt', 'w+')
f.write('hello world!')
f.seek(6)
print(f.read())
f.close()

world!


这里 `f.seek(6)` 移动到文件的第6个字符处，然后 `f.read()` 读出剩下的内容。

In [13]:
import os
os.remove('myfile.txt')

## 二进制文件

二进制读写模式 b：

In [14]:
import os
f = open('binary.bin', 'wb')
f.write(os.urandom(16))
f.close()

f = open('binary.bin', 'rb')
print(repr(f.read()))
f.close()

b'l\t\xc8\x82oRl\xb5g\xf8\x8c\xd1\xe6GwK'


In [15]:
import os
os.remove('binary.bin')

## 换行符

不同操作系统的换行符可能不同：

- `\r`
- `\n`
- `\r\n`

使用 `U` 选项，可以将这三个统一看成 `\n` 换行符。

## 关闭文件

在**Python**中，如果一个打开的文件不再被其他变量引用时，它会自动关闭这个文件。

所以正常情况下，如果一个文件正常被关闭了，忘记调用文件的 `close` 方法不会有什么问题。

关闭文件可以保证内容已经被写入文件，而不关闭可能会出现意想不到的结果：

In [16]:
f = open('newfile.txt','w')
f.write('hello world')
g = open('newfile.txt', 'r')
print(repr(g.read()))

''


虽然这里写了内容，但是在关闭之前，这个内容并没有被写入磁盘。

使用循环写入的内容也并不完整：

In [17]:
f = open('newfile.txt','w')
for i in range(3000):
    f.write('hello world: ' + str(i) + '\n')

g = open('newfile.txt', 'r')
print(g.read())
f.close()
g.close()

hello world: 0
hello world: 1
hello world: 2
hello world: 3
hello world: 4
hello world: 5
hello world: 6
hello world: 7
hello world: 8
hello world: 9
hello world: 10
hello world: 11
hello world: 12
hello world: 13
hello world: 14
hello world: 15
hello world: 16
hello world: 17
hello world: 18
hello world: 19
hello world: 20
hello world: 21
hello world: 22
hello world: 23
hello world: 24
hello world: 25
hello world: 26
hello world: 27
hello world: 28
hello world: 29
hello world: 30
hello world: 31
hello world: 32
hello world: 33
hello world: 34
hello world: 35
hello world: 36
hello world: 37
hello world: 38
hello world: 39
hello world: 40
hello world: 41
hello world: 42
hello world: 43
hello world: 44
hello world: 45
hello world: 46
hello world: 47
hello world: 48
hello world: 49
hello world: 50
hello world: 51
hello world: 52
hello world: 53
hello world: 54
hello world: 55
hello world: 56
hello world: 57
hello world: 58
hello world: 59
hello world: 60
hello world: 61
hello world: 62
he

In [18]:
import os
os.remove('newfile.txt')

出现异常时候的读写：

In [19]:
f = open('newfile.txt','w')
for i in range(3000):
    x = 1.0 / (i - 1000)
    f.write('hello world: ' + str(i) + '\n')

ZeroDivisionError: float division by zero

查看已有内容：

In [20]:
g = open('newfile.txt', 'r')
print(g.read())
f.close()
g.close()

hello world: 0
hello world: 1
hello world: 2
hello world: 3
hello world: 4
hello world: 5
hello world: 6
hello world: 7
hello world: 8
hello world: 9
hello world: 10
hello world: 11
hello world: 12
hello world: 13
hello world: 14
hello world: 15
hello world: 16
hello world: 17
hello world: 18
hello world: 19
hello world: 20
hello world: 21
hello world: 22
hello world: 23
hello world: 24
hello world: 25
hello world: 26
hello world: 27
hello world: 28
hello world: 29
hello world: 30
hello world: 31
hello world: 32
hello world: 33
hello world: 34
hello world: 35
hello world: 36
hello world: 37
hello world: 38
hello world: 39
hello world: 40
hello world: 41
hello world: 42
hello world: 43
hello world: 44
hello world: 45
hello world: 46
hello world: 47
hello world: 48
hello world: 49
hello world: 50
hello world: 51
hello world: 52
hello world: 53
hello world: 54
hello world: 55
hello world: 56
hello world: 57
hello world: 58
hello world: 59
hello world: 60
hello world: 61
hello world: 62
he

可以看到，出现异常的时候，磁盘的写入并没有完成，为此我们可以使用 `try/except/finally` 块来关闭文件，这里 `finally` 确保关闭文件，所有的写入已经完成。

In [21]:
f = open('newfile.txt','w')
try:
    for i in range(3000):
        x = 1.0 / (i - 1000)
        f.write('hello world: ' + str(i) + '\n')
except Exception:
    print("something bad happened")
finally:
    f.close()

something bad happened


In [22]:
g = open('newfile.txt', 'r')
print(g.read())
g.close()

hello world: 0
hello world: 1
hello world: 2
hello world: 3
hello world: 4
hello world: 5
hello world: 6
hello world: 7
hello world: 8
hello world: 9
hello world: 10
hello world: 11
hello world: 12
hello world: 13
hello world: 14
hello world: 15
hello world: 16
hello world: 17
hello world: 18
hello world: 19
hello world: 20
hello world: 21
hello world: 22
hello world: 23
hello world: 24
hello world: 25
hello world: 26
hello world: 27
hello world: 28
hello world: 29
hello world: 30
hello world: 31
hello world: 32
hello world: 33
hello world: 34
hello world: 35
hello world: 36
hello world: 37
hello world: 38
hello world: 39
hello world: 40
hello world: 41
hello world: 42
hello world: 43
hello world: 44
hello world: 45
hello world: 46
hello world: 47
hello world: 48
hello world: 49
hello world: 50
hello world: 51
hello world: 52
hello world: 53
hello world: 54
hello world: 55
hello world: 56
hello world: 57
hello world: 58
hello world: 59
hello world: 60
hello world: 61
hello world: 62
he

## with 方法

事实上，**Python**提供了更安全的方法，当 `with` 块的内容结束后，**Python**会自动调用它的`close` 方法，确保读写的安全：

In [23]:
with open('newfile.txt','w') as f:
    for i in range(3000):
        x = 1.0 / (i - 1000)
        f.write('hello world: ' + str(i) + '\n')

ZeroDivisionError: float division by zero

与 `try/exception/finally` 效果相同，但更简单。

In [24]:
g = open('newfile.txt', 'r')
print(g.read())
g.close()

hello world: 0
hello world: 1
hello world: 2
hello world: 3
hello world: 4
hello world: 5
hello world: 6
hello world: 7
hello world: 8
hello world: 9
hello world: 10
hello world: 11
hello world: 12
hello world: 13
hello world: 14
hello world: 15
hello world: 16
hello world: 17
hello world: 18
hello world: 19
hello world: 20
hello world: 21
hello world: 22
hello world: 23
hello world: 24
hello world: 25
hello world: 26
hello world: 27
hello world: 28
hello world: 29
hello world: 30
hello world: 31
hello world: 32
hello world: 33
hello world: 34
hello world: 35
hello world: 36
hello world: 37
hello world: 38
hello world: 39
hello world: 40
hello world: 41
hello world: 42
hello world: 43
hello world: 44
hello world: 45
hello world: 46
hello world: 47
hello world: 48
hello world: 49
hello world: 50
hello world: 51
hello world: 52
hello world: 53
hello world: 54
hello world: 55
hello world: 56
hello world: 57
hello world: 58
hello world: 59
hello world: 60
hello world: 61
hello world: 62
he

所以，写文件时候要确保文件被正确关闭。

In [25]:
import os
os.remove('newfile.txt')

## 序列化

在数据储存与传送的部分是指将一个对象存储至一个储存媒介，例如档案或是记亿体缓冲等，或者透过网络传送资料时进行编码的过程，可以是字节或是XML等格式。而字节的或XML编码格式可以还原完全相等的对象。这程序被应用在不同应用程序之间传送对象，以及服务器将对象储存到档案或数据库。相反的过程又称为反序列化。
方法有很多，常用的有利用pickle、json、或numpy

### 1. 利用pickle

In [2]:
import numpy as np
import pickle

In [3]:
help(pickle)

Help on module pickle:

NAME
    pickle - Create portable serialized representations of Python objects.

MODULE REFERENCE
    https://docs.python.org/3.6/library/pickle
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    See module copyreg for a mechanism for registering custom picklers.
    See module pickletools source for extensive comments.
    
    Classes:
    
        Pickler
        Unpickler
    
    Functions:
    
        dump(object, file)
        dumps(object) -> string
        load(file) -> object
        loads(string) -> object
    
    Misc variables:
    
        __version__
        format_version
        compatible_formats

CLASSES
    builtins.Exception(builtins.BaseException)
     

In [26]:
# 序列化
x = np.arange(2*3*4).reshape(2, 3, 4)

with open('./test.pickle','wb') as f:
    pickle.dump(x,f)
! file test.pickle

test.pickle: 8086 relocatable (Microsoft)


In [28]:
import os
os.remove('./test.pickle')

In [11]:
# 反序列化
with open('./test.pickle', 'rb') as f:
    x = pickle.load(f)
print(type(x))
print(x)

<class 'numpy.ndarray'>
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### 利用numpy序列化

Useful when storing and reading back numpy array data. Use the functions `numpy.save` and `numpy.load`:

In [14]:
M = np.random.randn(4, 4)

In [16]:
np.save("random-matrix.npy", M)

!file random-matrix.npy

random-matrix.npy: data


In [18]:
np.load("random-matrix.npy")

array([[-0.52376751, -0.38175773,  3.58778901,  1.20131397],
       [-0.48689743,  0.54309938, -0.45380192, -0.46477425],
       [-1.00725744,  0.62234738, -1.59968743, -0.10876003],
       [-1.0229911 ,  0.56405432,  0.14518491, -0.84552825]])

### Comma-separated values (CSV)

A very common file format for data files is comma-separated values (CSV), or related formats such as TSV (tab-separated values). To read data from such files into Numpy arrays we can use the `numpy.genfromtxt` or `numpy.loadtxt` function.

Using `numpy.genfromtxt` gives you some options like the parameters missing_values, filling_values that can help you dealing with an incomplete csv

In [19]:
!head stockholm_td_adj.dat

1800  1  1    -6.1    -6.1    -6.1 1
1800  1  2   -15.4   -15.4   -15.4 1
1800  1  3   -15.0   -15.0   -15.0 1
1800  1  4   -19.3   -19.3   -19.3 1
1800  1  5   -16.8   -16.8   -16.8 1
1800  1  6   -11.4   -11.4   -11.4 1
1800  1  7    -7.6    -7.6    -7.6 1
1800  1  8    -7.1    -7.1    -7.1 1
1800  1  9   -10.1   -10.1   -10.1 1
1800  1 10    -9.5    -9.5    -9.5 1


In [21]:
x0 = np.loadtxt('stockholm_td_adj.dat')

In [22]:
x1 = np.genfromtxt('stockholm_td_adj.dat')

In [24]:
(x0==x1).all()

True

In [25]:
np.savetxt('copy.dat',x0)
!file copy.dat

copy.dat: ASCII text


In [29]:
import os
os.remove('copy.dat')

## Reading netCDF data

forked from Unidata Python Workshop

## Interactively exploring a netCDF File

Let's explore a netCDF file from the *Atlantic Real-Time Ocean Forecast System*

first, import netcdf4-python and numpy

In [26]:
import netCDF4
import numpy as np

## Create a netCDF4.Dataset object
- **`f`** is a `Dataset` object, representing an open netCDF file.
- printing the object gives you summary information, similar to *`ncdump -h`*.

In [27]:
f = netCDF4.Dataset('./data/rtofs_glo_3dz_f006_6hrly_reg3.nc')
print(f) 

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    Conventions: CF-1.0
    title: HYCOM ATLb2.00
    institution: National Centers for Environmental Prediction
    source: HYCOM archive file
    experiment: 90.9
    history: archv2ncdf3z
    dimensions(sizes): MT(1), Y(850), X(712), Depth(10)
    variables(dimensions): float64 MT(MT), float64 Date(MT), float32 Depth(Depth), int32 Y(Y), int32 X(X), float32 Latitude(Y,X), float32 Longitude(Y,X), float32 u(MT,Depth,Y,X), float32 v(MT,Depth,Y,X), float32 temperature(MT,Depth,Y,X), float32 salinity(MT,Depth,Y,X)
    groups: 



## Access a netCDF variable
- variable objects stored by name in **`variables`** dict.
- print the variable yields summary info (including all the attributes).
- no actual data read yet (just have a reference to the variable object with metadata).

In [28]:
print(f.variables.keys()) # get all variable names
temp = f.variables['temperature']  # temperature variable
print(temp) 

odict_keys(['MT', 'Date', 'Depth', 'Y', 'X', 'Latitude', 'Longitude', 'u', 'v', 'temperature', 'salinity'])
<class 'netCDF4._netCDF4.Variable'>
float32 temperature(MT, Depth, Y, X)
    coordinates: Longitude Latitude Date
    standard_name: sea_water_potential_temperature
    units: degC
    _FillValue: 1.26765e+30
    valid_range: [ -5.07860279  11.14989948]
    long_name:   temp [90.9H]
unlimited dimensions: MT
current shape = (1, 10, 850, 712)
filling on


## List the Dimensions

- All variables in a netCDF file have an associated shape, specified by a list of dimensions.
- Let's list all the dimensions in this netCDF file.
- Note that the **`MT`** dimension is special (*`unlimited`*), which means it can be appended to.

In [29]:
for d in f.dimensions.items():
    print(d)

('MT', <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'MT', size = 1
)
('Y', <class 'netCDF4._netCDF4.Dimension'>: name = 'Y', size = 850
)
('X', <class 'netCDF4._netCDF4.Dimension'>: name = 'X', size = 712
)
('Depth', <class 'netCDF4._netCDF4.Dimension'>: name = 'Depth', size = 10
)


Each variable has a **`dimensions`** and a **`shape`** attribute.

In [30]:
temp.dimensions

('MT', 'Depth', 'Y', 'X')

In [31]:
temp.shape

(1, 10, 850, 712)

### Each dimension typically has a variable associated with it (called a *coordinate* variable).
- *Coordinate variables* are 1D variables that have the same name as dimensions.
- Coordinate variables and *auxiliary coordinate variables* (named by the *coordinates* attribute) locate values in time and space.

In [32]:
mt = f.variables['MT']
depth = f.variables['Depth']
x,y = f.variables['X'], f.variables['Y']
print(mt)
print(x)
print(y)

<class 'netCDF4._netCDF4.Variable'>
float64 MT(MT)
    long_name: time
    units: days since 1900-12-31 00:00:00
    calendar: standard
    axis: T
unlimited dimensions: MT
current shape = (1,)
filling on, default _FillValue of 9.969209968386869e+36 used

<class 'netCDF4._netCDF4.Variable'>
int32 X(X)
    point_spacing: even
    axis: X
unlimited dimensions: 
current shape = (712,)
filling on, default _FillValue of -2147483647 used

<class 'netCDF4._netCDF4.Variable'>
int32 Y(Y)
    point_spacing: even
    axis: Y
unlimited dimensions: 
current shape = (850,)
filling on, default _FillValue of -2147483647 used



## Accessing data from a netCDF variable object

- netCDF variables objects behave much like numpy arrays.
- slicing a netCDF variable object returns a numpy array with the data.
- Boolean array and integer sequence indexing behaves differently for netCDF variables than for numpy arrays. Only 1-d boolean arrays and integer sequences are allowed, and these indices work independently along each dimension (similar to the way vector subscripts work in fortran).

In [33]:
time = mt[:]  # Reads the netCDF variable MT, array of one element
print(time) 

[ 41023.25]


In [34]:
dpth = depth[:] # examine depth array
print(depth.dimensions)
print(dpth) 

('Depth',)
[    0.   100.   200.   400.   700.  1000.  2000.  3000.  4000.  5000.]


In [35]:
xx,yy = x[:],y[:]
print('shape of temp variable: %s' % repr(temp.shape))
tempslice = temp[0, dpth > 400, yy > yy.max()/2, xx > xx.max()/2]
print('shape of temp slice: %s' % repr(tempslice.shape))

shape of temp variable: (1, 10, 850, 712)
shape of temp slice: (6, 425, 356)


## What is the sea surface temperature and salinity at 50N, 140W?
### Finding the latitude and longitude indices of 50N, 140W

- The `X` and `Y` dimensions don't look like longitudes and latitudes
- Use the auxilary coordinate variables named in the `coordinates` variable attribute, `Latitude` and `Longitude`

In [36]:
print(x[:])

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [37]:
lat, lon = f.variables['Latitude'], f.variables['Longitude']
print(lat)
print(lon)
print(lat[:])

<class 'netCDF4._netCDF4.Variable'>
float32 Latitude(Y, X)
    standard_name: latitude
    units: degrees_north
unlimited dimensions: 
current shape = (850, 712)
filling on, default _FillValue of 9.969209968386869e+36 used

<class 'netCDF4._netCDF4.Variable'>
float32 Longitude(Y, X)
    standard_name: longitude
    units: degrees_east
unlimited dimensions: 
current shape = (850, 712)
filling on, default _FillValue of 9.969209968386869e+36 used

[[ 45.77320099  45.77320099  45.77320099 ...,  45.77320099  45.77320099
   45.77320099]
 [ 45.82899857  45.82899857  45.82899857 ...,  45.82899857  45.82899857
   45.82899857]
 [ 45.88470078  45.88470078  45.88470078 ...,  45.88470078  45.88470078
   45.88470078]
 ..., 
 [ 78.36325073  78.34516144  78.32701111 ...,  56.40559387  56.36401367
   56.32240677]
 [ 78.38998413  78.37184906  78.35365295 ...,  56.41108322  56.36948395
   56.32785034]
 [ 78.41667938  78.39850616  78.38025665 ...,  56.4165535   56.37493134
   56.33327103]]


Aha!  So we need to find array indices `iy` and `ix` such that `Latitude[iy, ix]` is close to 50.0 and `Longitude[iy, ix]` is close to -140.0 ...

In [38]:
# extract lat/lon values (in degrees) to numpy arrays
latvals = lat[:]; lonvals = lon[:] 
# a function to find the index of the point closest pt
# (in squared distance) to give lat/lon value.
def getclosest_ij(lats,lons,latpt,lonpt):
    # find squared distance of every point on grid
    dist_sq = (lats-latpt)**2 + (lons-lonpt)**2  
    # 1D index of minimum dist_sq element
    minindex_flattened = dist_sq.argmin()    
    # Get 2D index for latvals and lonvals arrays from 1D index
    return np.unravel_index(minindex_flattened, lats.shape)
iy_min, ix_min = getclosest_ij(latvals, lonvals, 50., -140)
print(iy_min)
print(ix_min)


122
486


### Now we have all the information we need to find our answer.

<table align="left">
  <tr>
    <th>Variable</th>
    <th>Index</th> 
  </tr>
  <tr>
    <td>MT</td>
    <td>0</td> 
  </tr>
  <tr>
    <td>Depth</td>
    <td>0</td> 
  </tr>
  <tr>
    <td>Y</td>
    <td>`iy_min`</td> 
  </tr>
  <tr>
    <td>X</td>
    <td>`ix_min`</td> 
  </tr>
</table>

### What is the sea surface temperature and salinity at the specified point?

In [39]:
sal = f.variables['salinity']
# Read values out of the netCDF file for temperature and salinity
print('%7.4f %s' % (temp[0,0,iy_min,ix_min], temp.units))
print('%7.4f %s' % (sal[0,0,iy_min,ix_min], sal.units))

 6.4631 degC
32.6572 psu


## Simple multi-file aggregation

What if you have a bunch of netcdf files, each with data for a different year, and you want to access all the data as if it were in one file?

In [40]:
!ls -l ./data/prmsl*nc

-rw-r--r--@ 1 hhuang  staff  8985332 May  3 08:57 ./data/prmsl.2000.nc
-rw-r--r--@ 1 hhuang  staff  8968789 May  3 08:57 ./data/prmsl.2001.nc
-rw-r--r--@ 1 hhuang  staff  8972796 May  3 08:57 ./data/prmsl.2002.nc
-rw-r--r--@ 1 hhuang  staff  8974435 May  3 08:57 ./data/prmsl.2003.nc
-rw-r--r--@ 1 hhuang  staff  8997438 May  3 08:57 ./data/prmsl.2004.nc
-rw-r--r--@ 1 hhuang  staff  8976678 May  3 08:57 ./data/prmsl.2005.nc
-rw-r--r--@ 1 hhuang  staff  8969714 May  3 08:57 ./data/prmsl.2006.nc
-rw-r--r--@ 1 hhuang  staff  8974360 May  3 08:57 ./data/prmsl.2007.nc
-rw-r--r--@ 1 hhuang  staff  8994260 May  3 08:57 ./data/prmsl.2008.nc
-rw-r--r--@ 1 hhuang  staff  8974678 May  3 08:57 ./data/prmsl.2009.nc
-rw-r--r--@ 1 hhuang  staff  8970732 May  3 08:57 ./data/prmsl.2010.nc
-rw-r--r--@ 1 hhuang  staff  8976285 May  3 08:57 ./data/prmsl.2011.nc


**`MFDataset`** uses file globbing to patch together all the files into one big Dataset.
You can also pass it a list of specific files.

Limitations:

- It can only  aggregate the data along the leftmost dimension of each variable.
- only works with `NETCDF3`, or `NETCDF4_CLASSIC` formatted files.
- kind of slow.

In [41]:
from netCDF4 import num2date
mf = netCDF4.MFDataset('./data/prmsl*nc')
times = mf.variables['time']
dates = num2date(times[:],times.units)
print('starting date = %s' % dates[0])
print('ending date = %s'% dates[-1])
prmsl = mf.variables['prmsl']
print('times shape = %s' % times.shape)
print('prmsl dimensions = %s, prmsl shape = %s' %\
     (prmsl.dimensions, prmsl.shape))

starting date = 2000-01-01 00:00:00
ending date = 2011-12-31 00:00:00
times shape = 4383
prmsl dimensions = ('time', 'lat', 'lon'), prmsl shape = (4383, 91, 180)


## Closing your netCDF file

It's good to close netCDF files, but not actually necessary when Dataset is open for read access only.


In [42]:
f.close()

## Write netCDF4 file

## Opening a file, creating a new Dataset

Let's create a new, empty netCDF file named '../data/new.nc', opened for writing.

Be careful, opening a file with 'w' will clobber any existing data (unless `clobber=False` is used, in which case an exception is raised if the file already exists).

- `mode='r'` is the default.
- `mode='a'` opens an existing file and allows for appending (does not clobber existing data)
- `format` can be one of `NETCDF3_CLASSIC`, `NETCDF3_64BIT`, `NETCDF4_CLASSIC` or `NETCDF4` (default). `NETCDF4_CLASSIC` uses HDF5 for the underlying storage layer (as does `NETCDF4`) but enforces the classic netCDF 3 data model so data can be read with older clients.  

In [43]:
try: ncfile.close()  # just to be safe, make sure dataset is not already open.
except: pass
ncfile = netCDF4.Dataset('./data/new.nc',mode='w',format='NETCDF4_CLASSIC') 
print(ncfile)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    dimensions(sizes): 
    variables(dimensions): 
    groups: 



## Creating dimensions

The **ncfile** object we created is a container for _dimensions_, _variables_, and _attributes_.   First, let's create some dimensions using the [`createDimension`](http://unidata.github.io/netcdf4-python/netCDF4.Dataset-class.html#createDimension) method.  

- Every dimension has a name and a length.  
- The name is a string that is used to specify the dimension to be used when creating a variable, and as a key to access the dimension object in the `ncfile.dimensions` dictionary.

Setting the dimension length to `0` or `None` makes it unlimited, so it can grow. 

- For `NETCDF4` files, any variable's dimension can be unlimited.  
- For `NETCDF4_CLASSIC` and `NETCDF3*` files, only one per variable can be unlimited, and it must be the leftmost (slowest varying) dimension.

In [44]:
lat_dim = ncfile.createDimension('lat', 73)     # latitude axis
lon_dim = ncfile.createDimension('lon', 144)    # longitude axis
time_dim = ncfile.createDimension('time', None) # unlimited axis (can be appended to).
for dim in ncfile.dimensions.items():
    print(dim)

('lat', <class 'netCDF4._netCDF4.Dimension'>: name = 'lat', size = 73
)
('lon', <class 'netCDF4._netCDF4.Dimension'>: name = 'lon', size = 144
)
('time', <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'time', size = 0
)


## Creating attributes

netCDF attributes can be created just like you would for any python object. 

- Best to adhere to established conventions (like the [CF](http://cfconventions.org/) conventions)
- We won't try to adhere to any specific convention here though.

In [45]:
ncfile.title='My model data'
print(ncfile.title)

My model data


In [46]:
ncfile.subtitle="My model data subtitle"
print(ncfile.subtitle)
print(ncfile)

My model data subtitle
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    title: My model data
    subtitle: My model data subtitle
    dimensions(sizes): lat(73), lon(144), time(0)
    variables(dimensions): 
    groups: 



Try adding some more attributes...

## Creating variables

Now let's add some variables and store some data in them.  

- A variable has a name, a type, a shape, and some data values.  
- The shape of a variable is specified by a tuple of dimension names.  
- A variable should also have some named attributes, such as 'units', that describe the data.

The [`createVariable`](http://unidata.github.io/netcdf4-python/netCDF4.Dataset-class.html#createVariable) method takes 3 mandatory args.

- the 1st argument is the variable name (a string). This is used as the key to access the variable object from the `variables` dictionary.
- the 2nd argument is the datatype (most numpy datatypes supported).  
- the third argument is a tuple containing the dimension names (the dimensions must be created first).  Unless this is a `NETCDF4` file, any unlimited dimension must be the leftmost one.
- there are lots of optional arguments (many of which are only relevant when `format='NETCDF4'`) to control compression, chunking, fill_value, etc.


In [47]:
# Define two variables with the same names as dimensions,
# a conventional way to define "coordinate variables".
lat = ncfile.createVariable('lat', np.float32, ('lat',))
lat.units = 'degrees_north'
lat.long_name = 'latitude'
lon = ncfile.createVariable('lon', np.float32, ('lon',))
lon.units = 'degrees_east'
lon.long_name = 'longitude'
time = ncfile.createVariable('time', np.float64, ('time',))
time.units = 'hours since 1800-01-01'
time.long_name = 'time'
# Define a 3D variable to hold the data
temp = ncfile.createVariable('temp',np.float64,('time','lat','lon')) # note: unlimited dimension is leftmost
temp.units = 'K' # degrees Kelvin
temp.standard_name = 'air_temperature' # this is a CF standard name
print(temp)

<class 'netCDF4._netCDF4.Variable'>
float64 temp(time, lat, lon)
    units: K
    standard_name: air_temperature
unlimited dimensions: time
current shape = (0, 73, 144)
filling on, default _FillValue of 9.969209968386869e+36 used



## Pre-defined variable attributes (read only)

The netCDF4 module provides some useful pre-defined Python attributes for netCDF variables, such as dimensions, shape, dtype, ndim. 

Note: since no data has been written yet, the length of the 'time' dimension is 0.

In [48]:
print("-- Some pre-defined attributes for variable temp:")
print("temp.dimensions:", temp.dimensions)
print("temp.shape:", temp.shape)
print("temp.dtype:", temp.dtype)
print("temp.ndim:", temp.ndim)


-- Some pre-defined attributes for variable temp:
temp.dimensions: ('time', 'lat', 'lon')
temp.shape: (0, 73, 144)
temp.dtype: float64
temp.ndim: 3


## Writing data

To write data a netCDF variable object, just treat it like a numpy array and assign values to a slice.

In [49]:
nlats = len(lat_dim); nlons = len(lon_dim); ntimes = 3
# Write latitudes, longitudes.
# Note: the ":" is necessary in these "write" statements
lat[:] = -90. + (180./nlats)*np.arange(nlats) # south pole to north pole
lon[:] = (180./nlats)*np.arange(nlons) # Greenwich meridian eastward
# create a 3D array of random numbers
data_arr = np.random.uniform(low=280,high=330,size=(ntimes,nlats,nlons))
# Write the data.  This writes the whole 3D netCDF variable all at once.
temp[:,:,:] = data_arr  # Appends data along unlimited dimension
print("-- Wrote data, temp.shape is now ", temp.shape)
# read data back from variable (by slicing it), print min and max
print("-- Min/Max values:", temp[:,:,:].min(), temp[:,:,:].max())

-- Wrote data, temp.shape is now  (3, 73, 144)
-- Min/Max values: 280.001548423 329.998000044


- You can just treat a netCDF Variable object like a numpy array and assign values to it.
- Variables automatically grow along unlimited dimensions (unlike numpy arrays)
- The above writes the whole 3D variable all at once,  but you can write it a slice at a time instead.

Let's add another time slice....


In [50]:
# create a 2D array of random numbers
data_slice = np.random.uniform(low=280,high=330,size=(nlats,nlons))
temp[3,:,:] = data_slice   # Appends the 4th time slice
print("-- Wrote more data, temp.shape is now ", temp.shape)

-- Wrote more data, temp.shape is now  (4, 73, 144)


Note that we have not yet written any data to the time variable.  It automatically grew as we appended data along the time dimension to the variable `temp`, but the data is missing.

In [51]:
print(time)
times_arr = time[:]
print(type(times_arr),times_arr)  # dashes indicate masked values (where data has not yet been written)

<class 'netCDF4._netCDF4.Variable'>
float64 time(time)
    units: hours since 1800-01-01
    long_name: time
unlimited dimensions: time
current shape = (4,)
filling on, default _FillValue of 9.969209968386869e+36 used

<class 'numpy.ma.core.MaskedArray'> [-- -- -- --]


Let's add/write some data into the time variable.  

- Given a set of datetime instances, use date2num to convert to numeric time values and then write that data to the variable.

In [52]:
import datetime as dt
from netCDF4 import date2num,num2date
# 1st 4 days of October.
dates = [dt.datetime(2014,10,1,0),dt.datetime(2014,10,2,0),dt.datetime(2014,10,3,0),dt.datetime(2014,10,4,0)]
print(dates)

[datetime.datetime(2014, 10, 1, 0, 0), datetime.datetime(2014, 10, 2, 0, 0), datetime.datetime(2014, 10, 3, 0, 0), datetime.datetime(2014, 10, 4, 0, 0)]


In [53]:
times = date2num(dates, time.units)
print(times, time.units) # numeric values

[ 1882440.  1882464.  1882488.  1882512.] hours since 1800-01-01


In [54]:
time[:] = times
# read time data back, convert to datetime instances, check values.
print(time[:])
print(time.units)
print(num2date(time[:],time.units))


[ 1882440.  1882464.  1882488.  1882512.]
hours since 1800-01-01
[datetime.datetime(2014, 10, 1, 0, 0) datetime.datetime(2014, 10, 2, 0, 0)
 datetime.datetime(2014, 10, 3, 0, 0) datetime.datetime(2014, 10, 4, 0, 0)]


## Closing a netCDF file

It's **important** to close a netCDF file you opened for writing:

- flushes buffers to make sure all data gets written
- releases memory resources used by open netCDF files

In [55]:
# first print the Dataset object to see what we've got
print(ncfile)
# close the Dataset.
ncfile.close(); print('Dataset is closed!')

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    title: My model data
    subtitle: My model data subtitle
    dimensions(sizes): lat(73), lon(144), time(4)
    variables(dimensions): float32 lat(lat), float32 lon(lon), float64 time(time), float64 temp(time,lat,lon)
    groups: 

Dataset is closed!


In [56]:
!ncdump -h ./data/new.nc

netcdf new {
dimensions:
	lat = 73 ;
	lon = 144 ;
	time = UNLIMITED ; // (4 currently)
variables:
	float lat(lat) ;
		lat:units = "degrees_north" ;
		lat:long_name = "latitude" ;
	float lon(lon) ;
		lon:units = "degrees_east" ;
		lon:long_name = "longitude" ;
	double time(time) ;
		time:units = "hours since 1800-01-01" ;
		time:long_name = "time" ;
	double temp(time, lat, lon) ;
		temp:units = "K" ;
		temp:standard_name = "air_temperature" ;

// global attributes:
		:_NCProperties = "version=1|netcdflibversion=4.4.1|hdf5libversion=1.8.17" ;
		:title = "My model data" ;
		:subtitle = "My model data subtitle" ;
}


# Advanced features

So far we've only exercised features associated with the old netCDF version 3 data model.  netCDF version 4 adds a lot of new functionality that comes with the more flexible HDF5 storage layer.  

Let's create a new file with `format='NETCDF4'` so we can try out some of these features.

In [57]:
ncfile = netCDF4.Dataset('./data/new2.nc','w',format='NETCDF4')
print(ncfile)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    dimensions(sizes): 
    variables(dimensions): 
    groups: 



## Creating Groups

netCDF version 4 added support for organizing data in hierarchical groups.

- analagous to directories in a filesystem. 
- Groups serve as containers for variables, dimensions and attributes, as well as other groups. 
- A `netCDF4.Dataset` creates a special group, called the 'root group', which is similar to the root directory in a unix filesystem. 

- groups are created using the [`createGroup`](http://unidata.github.io/netcdf4-python/netCDF4.Dataset-class.html#createGroup) method.
- takes a single argument (a string, which is the name of the Group instance).  This string is used as a key to access the group instances in the `groups` dictionary.

Here we create two groups to hold data for two different model runs.

In [58]:
grp1 = ncfile.createGroup('model_run1')
grp2 = ncfile.createGroup('model_run2')
for grp in ncfile.groups.items():
    print(grp)

('model_run1', <class 'netCDF4._netCDF4.Group'>
group /model_run1:
    dimensions(sizes): 
    variables(dimensions): 
    groups: 
)
('model_run2', <class 'netCDF4._netCDF4.Group'>
group /model_run2:
    dimensions(sizes): 
    variables(dimensions): 
    groups: 
)


Create some dimensions in the root group.

In [59]:
lat_dim = ncfile.createDimension('lat', 73)     # latitude axis
lon_dim = ncfile.createDimension('lon', 144)    # longitude axis
time_dim = ncfile.createDimension('time', None) # unlimited axis (can be appended to).

Now create a variable in grp1 and grp2.  The library will search recursively upwards in the group tree to find the dimensions (which in this case are defined one level up).

- These variables are create with **zlib compression**, another nifty feature of netCDF 4. 
- The data are automatically compressed when data is written to the file, and uncompressed when the data is read.  
- This can really save disk space, especially when used in conjunction with the [**least_significant_digit**](http://unidata.github.io/netcdf4-python/netCDF4.Dataset-class.html#createVariable) keyword argument, which causes the data to be quantized (truncated) before compression.  This makes the compression lossy, but more efficient.

In [60]:
temp1 = grp1.createVariable('temp',np.float64,('time','lat','lon'),zlib=True)
temp2 = grp2.createVariable('temp',np.float64,('time','lat','lon'),zlib=True)
for grp in ncfile.groups.items():  # shows that each group now contains 1 variable
    print(grp)

('model_run1', <class 'netCDF4._netCDF4.Group'>
group /model_run1:
    dimensions(sizes): 
    variables(dimensions): float64 temp(time,lat,lon)
    groups: 
)
('model_run2', <class 'netCDF4._netCDF4.Group'>
group /model_run2:
    dimensions(sizes): 
    variables(dimensions): float64 temp(time,lat,lon)
    groups: 
)


## Creating a variable with a compound data type

- Compound data types map directly to numpy structured (a.k.a 'record' arrays). 
- Structured arrays are akin to C structs, or derived types in Fortran. 
- They allow for the construction of table-like structures composed of combinations of other data types, including other compound types. 
- Might be useful for representing multiple parameter values at each point on a grid, or at each time and space location for scattered (point) data. 

Here we create a variable with a compound data type to represent complex data (there is no native complex data type in netCDF). 

- The compound data type is created with the [`createCompoundType`](http://unidata.github.io/netcdf4-python/netCDF4.Dataset-class.html#createCompoundType) method.

In [61]:
# create complex128 numpy structured data type
complex128 = np.dtype([('real',np.float64),('imag',np.float64)])
# using this numpy dtype, create a netCDF compound data type object
# the string name can be used as a key to access the datatype from the cmptypes dictionary.
complex128_t = ncfile.createCompoundType(complex128,'complex128')
# create a variable with this data type, write some data to it.
cmplxvar = grp1.createVariable('cmplx_var',complex128_t,('time','lat','lon'))
# write some data to this variable
# first create some complex random data
nlats = len(lat_dim); nlons = len(lon_dim)
data_arr_cmplx = np.random.uniform(size=(nlats,nlons))+1.j*np.random.uniform(size=(nlats,nlons))
# write this complex data to a numpy complex128 structured array
data_arr = np.empty((nlats,nlons),complex128)
data_arr['real'] = data_arr_cmplx.real; data_arr['imag'] = data_arr_cmplx.imag
cmplxvar[0] = data_arr  # write the data to the variable (appending to time dimension)
print(cmplxvar)
data_out = cmplxvar[0] # read one value of data back from variable
print(data_out.dtype, data_out.shape, data_out[0,0])

<class 'netCDF4._netCDF4.Variable'>
compound cmplx_var(time, lat, lon)
compound data type: [('real', '<f8'), ('imag', '<f8')]
path = /model_run1
unlimited dimensions: time
current shape = (1, 73, 144)

[('real', '<f8'), ('imag', '<f8')] (73, 144) (0.39709232215674795, 0.40637375644863405)


## Creating a variable with a variable-length (vlen) data type

netCDF 4 has support for variable-length or "ragged" arrays. These are arrays of variable length sequences having the same type. 

- To create a variable-length data type, use the [`createVLType`](http://unidata.github.io/netcdf4-python/netCDF4.Dataset-class.html#createVLType) method.
- The numpy datatype of the variable-length sequences and the name of the new datatype must be specified. 

In [62]:
vlen_t = ncfile.createVLType(np.int64, 'phony_vlen')

A new variable can then be created using this datatype.

In [63]:
vlvar = grp2.createVariable('phony_vlen_var', vlen_t, ('time','lat','lon'))

Since there is no native vlen datatype in numpy, vlen arrays are represented in python as object arrays (arrays of dtype `object`). 

- These are arrays whose elements are Python object pointers, and can contain any type of python object. 
- For this application, they must contain 1-D numpy arrays all of the same type but of varying length. 
- Fill with 1-D random numpy int64 arrays of random length between 1 and 10.

In [64]:
vlen_data = np.empty((nlats,nlons),object)
for i in range(nlons):
    for j in range(nlats):
        size = np.random.randint(1,10,size=1) # random length of sequence
        vlen_data[j,i] = np.random.randint(0,10,size=size).astype(vlen_t.dtype)# generate random sequence
vlvar[0] = vlen_data # append along unlimited dimension (time)
print(vlvar)
print('data =\n',vlvar[:])

<class 'netCDF4._netCDF4.Variable'>
vlen phony_vlen_var(time, lat, lon)
vlen data type: int64
path = /model_run2
unlimited dimensions: time
current shape = (1, 73, 144)

data =
 [[[array([8, 9, 7, 4, 7, 0, 0, 6, 3]) array([4, 2, 7, 0, 9, 4, 1])
   array([3, 2, 1, 3, 3, 7]) ..., array([2, 0, 0, 2, 2, 4])
   array([9, 1, 2, 8, 9, 8]) array([0, 1, 3, 1, 4])]
  [array([2, 4, 1]) array([3]) array([8, 9, 0]) ..., array([8, 1])
   array([6, 1, 2, 1, 4, 2]) array([0, 5, 4, 8, 2])]
  [array([7]) array([9, 2, 8, 3, 0, 7]) array([2, 2, 7]) ..., array([3, 5])
   array([1, 7]) array([4])]
  ..., 
  [array([8, 7]) array([5, 7, 2, 4]) array([1, 9, 8, 6, 9]) ...,
   array([5, 7, 0, 9, 2]) array([5]) array([4, 9, 4, 8, 3, 3, 7, 2, 9])]
  [array([6, 3, 5, 4, 2, 1, 4]) array([4, 3, 0, 6, 5, 0, 3, 4, 6])
   array([4, 9]) ..., array([3, 0, 6, 2, 5, 5]) array([8, 9, 2])
   array([7, 8, 9, 4, 6, 1, 7, 3])]
  [array([5, 7, 4, 6, 8, 0, 2]) array([6, 3, 6, 8, 6, 3, 4]) array([8, 1])
   ..., array([8, 9, 9, 3, 7

Close the Dataset and examine the contents with ncdump.

In [65]:
ncfile.close()
!ncdump -h ./data/new2.nc

netcdf new2 {
types:
  compound complex128 {
    double real ;
    double imag ;
  }; // complex128
  int64(*) phony_vlen ;
dimensions:
	lat = 73 ;
	lon = 144 ;
	time = UNLIMITED ; // (1 currently)

// global attributes:
		:_NCProperties = "version=1|netcdflibversion=4.4.1|hdf5libversion=1.8.17" ;

group: model_run1 {
  variables:
  	double temp(time, lat, lon) ;
  	complex128 cmplx_var(time, lat, lon) ;
  } // group model_run1

group: model_run2 {
  variables:
  	double temp(time, lat, lon) ;
  	phony_vlen phony_vlen_var(time, lat, lon) ;
  } // group model_run2
}


## Other interesting and useful projects using netcdf4-python

- [xarray](http://xarray.pydata.org): N-dimensional variant of the core [pandas](http://pandas.pydata.org) data structure that can operate on netcdf variables.
- [Iris](http://scitools.org.uk/iris/): a data model to create a data abstraction layer which isolates analysis and visualisation code from data format specifics.  Uses netcdf4-python to access netcdf data (can also handle GRIB).
- [Biggus](https://github.com/SciTools/biggus): Virtual large arrays (from netcdf variables) with lazy evaluation.
- [cf-python](http://cfpython.bitbucket.org/): Implements the [CF](http://cfconventions.org) data model for the reading, writing and processing of data and metadata. 